version: '3'
services:
  app:
    container_name: fiber
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    container_name: roach
    image: cockroachdb/cockroach
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    restart: always
    environment:
      - COCKROACH_DATABASE=products
      - COCKROACH_USER=gorm
      - COCKROACH_PASSWORD=gorm
      - COCKROACH_INSECURE=true
    volumes:
      - "roach-single:/cockroach/cockroach-data"

volumes:
  roach-single: