version: '3'
services:
  app:
    container_name: fiber
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: roach
    image: cockroachdb/cockroach
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    restart: always
    volumes:
      - "roach-single:/cockroach/cockroach-data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/#/overview/list"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  roach-single: