version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: cockroachdb/cockroach
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    restart: always
    environment:
      - COCKROACH_DATABASE=auth
      - COCKROACH_USER=root
      - COCKROACH_PASSWORD=root
      - COCKROACH_INSECURE=true
    volumes:
      - "roach-single:/cockroach/cockroach-data"