basePath: /
host: localhost:3000
info:
  contact: {}
  description: Go Fiber REST API with Swagger Example
  title: Go Fiber REST API with Swagger Example
  version: "1"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: Hello World.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Hello World.
      tags:
      - home
  /api:
    get:
      consumes:
      - application/json
      description: AuthReq middleware
      produces:
      - application/json
      responses: {}
      summary: AuthReq middleware
      tags:
      - middleware
    post:
      consumes:
      - '*/*'
      description: Create a product
      parameters:
      - description: Product Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Product Description
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: Product Category
        in: body
        name: category
        required: true
        schema:
          type: string
      - description: Product Amount
        in: body
        name: amount
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create a product
      tags:
      - products
  /api/{id}:
    delete:
      consumes:
      - '*/*'
      description: Delete a product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - '*/*'
      description: Get a product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get a product
      tags:
      - products
    put:
      consumes:
      - '*/*'
      description: Update a product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Product Description
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: Product Category
        in: body
        name: category
        required: true
        schema:
          type: string
      - description: Product Amount
        in: body
        name: amount
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update a product
      tags:
      - products
  /auth:
    get:
      consumes:
      - application/json
      description: Auth middleware
      produces:
      - application/json
      responses: {}
      summary: Auth middleware
      tags:
      - middleware
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - health
schemes:
- http
swagger: "2.0"
